### ISSUE TITLE
Looking to connect to solve a problem in return for $$

### ISSUE THREAD

**Issue by sibaGit** [ColorsWind/algorimatrix#8]
Hello ColorsWind, is this you? https://stackoverflow.com/users/18788966/colorswind

If so, I'm looking to connect in regards to an issue in which a client of mine needs to build a universal binary of FFMPEG that includes both the x86_64 and arm64 architectures.

Per this discussion on StackOverflow; https://stackoverflow.com/questions/71683881/ffmpeg-refuses-to-compile-for-x86-64-arch-on-m1-mac
it would appear you know how to solve this problem?

I can make it worth your time, here's my email; GerryPerez96@gmail.com

**Comment by ColorsWind** [comment]
Hello Gerry Perez, I have already sent an email to provide some information for you.
